name: Swift Package CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Module
        run: xcodebuild build -scheme SharedMovieModule -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
